/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.bongole.ti.gpuimage;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="Android", id="com.bongole.ti.gpuimage")
public class AndroidModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "AndroidModule";
	private static final boolean DBG = TiConfig.LOGD;
	
	@Kroll.constant public static final String SEPIA_FILTER = "sepia";
	@Kroll.constant public static final String MONOCHROME_FILTER = "monochrome";
	@Kroll.constant public static final String GRAYSCALE_FILTER = "grayscale";
	@Kroll.constant public static final String DIRECTIONAL_SOBEL_EDGE_DETECTION_FILETER = "directional_sobel_edge_detection";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public AndroidModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}


}

